---
- name: Configure firewalld
  firewalld:
    port: "{{ open_port }}/{{ open_protocol | default('tcp', true) }}"
    state: "{{ open_state | default('enabled', true) }}"
    permanent: true
    immediate: true

- name: Configure firewalld
  firewalld:
    port: "{{ open_port }}/{{ open_protocol | default('udp', true) }}"
    state: "{{ open_state | default('enabled', true) }}"
    permanent: true
    immediate: true
