---
- name: Configure firewalld
  firewalld:
    port: "{{ open_port }}/{{ open_protocol | default('tcp', true) }}"
    state: enabled
    permanent: yes
    immediate: yes

- name: Configure firewalld
  firewalld:
    port: "{{ open_port }}/{{ open_protocol | default('udp', true) }}"
    state: enabled
    permanent: yes
    immediate: yes
