---
- name: Gathering Service Facts
  service_facts: {}

- name: Include tasks for firewalld
  include_tasks: firewalld.yml
  when:
  - services["firewalld.service"] is defined
  - services["firewalld.service"].state == "running"
